name: Update Docker Hub Description
on:
  push:
    branches:
      - master
    paths:
      - docker/README.md
      - .github/workflows/dockerhub-description.yml
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v5
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PAT }}
        DOCKERHUB_REPOSITORY: wmbusmeters/wmbusmeters
        README_FILEPATH: ./docker/README.md
